# AI Room Cleaner Addon Configuration
name: "AI Room Cleaner"
version: "0.1.0"
slug: "ai_room_cleaner"
description: "An intelligent cleanliness assistant using a multimodal AI to keep your room tidy."
arch:
  - "aarch64"
  - "amd64"
  - "armv7"
init: false
panel_icon: "mdi:robot-vacuum"
ingress: true
ingress_port: 8000
startup: "application"
boot: "auto"
ports:
  8000/tcp: null
ports_description:
  8000/tcp: "Web interface for the AI Room Cleaner"
options:
  camera_entity: ""
  api_key: ""
  ai_model: "gemini-2.5-pro"
  update_frequency: 60
  prompt: "Describe the state of the room and identify any items that are out of place."
schema:
  camera_entity: "str"
  api_key: "password"
  ai_model: "str"
  update_frequency: "int(1,1440)"
  prompt: "text"